FROM node:20-alpine

WORKDIR /app

# Menginstal dependensi terpisah agar proses rebuild layer lebih cepat
COPY package*.json ./
RUN npm install --legacy-peer-deps

# Kode akan di-mount menggunakan volume di docker-compose, 
# tapi kita COPY tetap untuk inisialisasi awal jika dibutuhkan
COPY . .

# Port default Vue CLI
EXPOSE 8080

CMD ["npm", "run", "serve"]
