/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers: never
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/(main)': RouteRecordInfo<
      '/(main)',
      '/',
      Record<never, never>,
      Record<never, never>,
      | '/(main)/crm/clients'
      | '/(main)/crm/invoices'
      | '/(main)/crm/projects'
      | '/(main)/dashboard/default'
      | '/(main)/management/components/ChangePasswordDialog'
      | '/(main)/management/components/DeleteTenantDialog'
      | '/(main)/management/components/TenantFormDialog'
      | '/(main)/management/components/UserFormDialog'
      | '/(main)/management/tenants'
      | '/(main)/management/users'
      | '/(main)/profile'
      | '/(main)/settings'
    >,
    '/(main)/crm/clients': RouteRecordInfo<
      '/(main)/crm/clients',
      '/crm/clients',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(main)/crm/invoices': RouteRecordInfo<
      '/(main)/crm/invoices',
      '/crm/invoices',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(main)/crm/projects': RouteRecordInfo<
      '/(main)/crm/projects',
      '/crm/projects',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(main)/dashboard/default': RouteRecordInfo<
      '/(main)/dashboard/default',
      '/dashboard/default',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(main)/management/components/ChangePasswordDialog': RouteRecordInfo<
      '/(main)/management/components/ChangePasswordDialog',
      '/management/components/ChangePasswordDialog',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(main)/management/components/DeleteTenantDialog': RouteRecordInfo<
      '/(main)/management/components/DeleteTenantDialog',
      '/management/components/DeleteTenantDialog',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(main)/management/components/TenantFormDialog': RouteRecordInfo<
      '/(main)/management/components/TenantFormDialog',
      '/management/components/TenantFormDialog',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(main)/management/components/UserFormDialog': RouteRecordInfo<
      '/(main)/management/components/UserFormDialog',
      '/management/components/UserFormDialog',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(main)/management/tenants': RouteRecordInfo<
      '/(main)/management/tenants',
      '/management/tenants',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(main)/management/users': RouteRecordInfo<
      '/(main)/management/users',
      '/management/users',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(main)/profile': RouteRecordInfo<
      '/(main)/profile',
      '/profile',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(main)/settings': RouteRecordInfo<
      '/(main)/settings',
      '/settings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/authentication/forgot-password': RouteRecordInfo<
      '/authentication/forgot-password',
      '/authentication/forgot-password',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/authentication/login': RouteRecordInfo<
      '/authentication/login',
      '/authentication/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/authentication/register': RouteRecordInfo<
      '/authentication/register',
      '/authentication/register',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/authentication/reset-password': RouteRecordInfo<
      '/authentication/reset-password',
      '/authentication/reset-password',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/maintenance/error': RouteRecordInfo<
      '/maintenance/error',
      '/maintenance/error',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/(main).vue': {
      routes:
        | '/(main)'
        | '/(main)/crm/clients'
        | '/(main)/crm/invoices'
        | '/(main)/crm/projects'
        | '/(main)/dashboard/default'
        | '/(main)/management/components/ChangePasswordDialog'
        | '/(main)/management/components/DeleteTenantDialog'
        | '/(main)/management/components/TenantFormDialog'
        | '/(main)/management/components/UserFormDialog'
        | '/(main)/management/tenants'
        | '/(main)/management/users'
        | '/(main)/profile'
        | '/(main)/settings'
      views:
        | 'default'
    }
    'src/pages/(main)/crm/clients.vue': {
      routes:
        | '/(main)/crm/clients'
      views:
        | never
    }
    'src/pages/(main)/crm/invoices.vue': {
      routes:
        | '/(main)/crm/invoices'
      views:
        | never
    }
    'src/pages/(main)/crm/projects.vue': {
      routes:
        | '/(main)/crm/projects'
      views:
        | never
    }
    'src/pages/(main)/dashboard/default.vue': {
      routes:
        | '/(main)/dashboard/default'
      views:
        | never
    }
    'src/pages/(main)/management/components/ChangePasswordDialog.vue': {
      routes:
        | '/(main)/management/components/ChangePasswordDialog'
      views:
        | never
    }
    'src/pages/(main)/management/components/DeleteTenantDialog.vue': {
      routes:
        | '/(main)/management/components/DeleteTenantDialog'
      views:
        | never
    }
    'src/pages/(main)/management/components/TenantFormDialog.vue': {
      routes:
        | '/(main)/management/components/TenantFormDialog'
      views:
        | never
    }
    'src/pages/(main)/management/components/UserFormDialog.vue': {
      routes:
        | '/(main)/management/components/UserFormDialog'
      views:
        | never
    }
    'src/pages/(main)/management/tenants.vue': {
      routes:
        | '/(main)/management/tenants'
      views:
        | never
    }
    'src/pages/(main)/management/users.vue': {
      routes:
        | '/(main)/management/users'
      views:
        | never
    }
    'src/pages/(main)/profile.vue': {
      routes:
        | '/(main)/profile'
      views:
        | never
    }
    'src/pages/(main)/settings.vue': {
      routes:
        | '/(main)/settings'
      views:
        | never
    }
    'src/pages/authentication/forgot-password.vue': {
      routes:
        | '/authentication/forgot-password'
      views:
        | never
    }
    'src/pages/authentication/login.vue': {
      routes:
        | '/authentication/login'
      views:
        | never
    }
    'src/pages/authentication/register.vue': {
      routes:
        | '/authentication/register'
      views:
        | never
    }
    'src/pages/authentication/reset-password.vue': {
      routes:
        | '/authentication/reset-password'
      views:
        | never
    }
    'src/pages/maintenance/error.vue': {
      routes:
        | '/maintenance/error'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
